// AI SYSTEM
constexpr float LOD_PA_MIN_DISTANCE		= 130.f;
constexpr float PATROL_MIN_DISTANCE		= 100.f;
constexpr float VIEW_MIN_DISTANCE		= 10.f;
constexpr float PURSUE_MIN_DISTANCE		= 15.f;
constexpr float ARRIVE_MIN_DISTANCE	    = 2.f;
constexpr float ATTACK_MIN_DISTANCE		= 0.f;

constexpr float LOD_PA_MIN_DISTANCE2	= LOD_PA_MIN_DISTANCE * LOD_PA_MIN_DISTANCE;
constexpr float PATROL_MIN_DISTANCE2	= PATROL_MIN_DISTANCE * PATROL_MIN_DISTANCE;
constexpr float VIEW_MIN_DISTANCE2	    = VIEW_MIN_DISTANCE   * VIEW_MIN_DISTANCE;
constexpr float PURSUE_MIN_DISTANCE2	= PURSUE_MIN_DISTANCE * PURSUE_MIN_DISTANCE;
constexpr float ARRIVE_MIN_DISTANCE2	= ARRIVE_MIN_DISTANCE * ARRIVE_MIN_DISTANCE;
constexpr float ATTACK_MIN_DISTANCE2	= ATTACK_MIN_DISTANCE * ATTACK_MIN_DISTANCE;

