// AI SYSTEM
constexpr float PATROL_MIN_DISTANCE		= 100.f;
constexpr float PURSUE_MIN_DISTANCE		= 10.f;
constexpr float ATTACK_MIN_DISTANCE		= 0.f;

constexpr float PATROL_MIN_DISTANCE2	= PATROL_MIN_DISTANCE * PATROL_MIN_DISTANCE;
constexpr float PURSUE_MIN_DISTANCE2	= PURSUE_MIN_DISTANCE * PURSUE_MIN_DISTANCE;
constexpr float ATTACK_MIN_DISTANCE2	= ATTACK_MIN_DISTANCE * ATTACK_MIN_DISTANCE;

constexpr float CHASE_MIN_DISTANCE      = 40.f;
constexpr float ARRIVED_MIN_DISTANCE	= 2.f;

constexpr float CHASE_MIN_DISTANCE2     = CHASE_MIN_DISTANCE * CHASE_MIN_DISTANCE;
constexpr float ARRIVED_MIN_DISTANCE2	= ARRIVED_MIN_DISTANCE * ARRIVED_MIN_DISTANCE;
