#pragma once

#include <sys/VelocitySystem.hpp>
#include <sys/InputSystem.hpp>
#include <sys/MovementSystem.hpp>
#include <sys/AI_System.hpp>
#include <sys/AttackSystem.hpp>
#include <sys/TriggerFastCollisionSystem.hpp>
#include <sys/RigidBodySystem.hpp>
#include <sys/TriggerCollisionSystem.hpp>
#include <sys/TriggerResolutionSystem.hpp>
#include <sys/CooldownSystem.hpp>
#include <sys/BulletDataSystem.hpp>
#include <sys/DeathSystem.hpp>
#include <sys/SoundSystem.hpp>
#include <sys/RenderSystem.hpp>
#include <sys/VideoSystem.hpp>
#include <sys/CollisionSystem.hpp>
#include <sys/HUDintroSystem.hpp>
#include <sys/IntroInputSystem.hpp>
#include <sys/HUDingameSystem.hpp>